# Generated by Django 4.2.20 on 2026-05-11 00:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='Acción')),
                ('target', models.CharField(blank=True, default='-', max_length=255, verbose_name='Objetivo')),
                ('action_type', models.CharField(choices=[('create', 'Creación'), ('edit', 'Edición'), ('delete', 'Eliminación'), ('approve', 'Aprobación'), ('reject', 'Rechazo'), ('upload', 'Subida'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('backup', 'Respaldo')], max_length=20, verbose_name='Tipo de acción')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Actividad',
                'verbose_name_plural': 'Registros de Actividad',
                'ordering': ['-created_at'],
            },
        ),
    ]
