# Generated by Django 4.2.20 on 2026-06-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_activitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='action_type',
            field=models.CharField(choices=[('create', 'Creación'), ('edit', 'Edición'), ('delete', 'Eliminación'), ('approve', 'Aprobación'), ('reject', 'Rechazo'), ('upload', 'Subida'), ('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('backup', 'Respaldo')], db_index=True, max_length=20, verbose_name='Tipo de acción'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha/Hora'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('asignado', 'Asignado'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('revision', 'En Revisión'), ('correccion', 'Correccion Requerida'), ('info', 'Informacion')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='read',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
