services:

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: gestor_expedientes
      POSTGRES_USER: ge_user
      POSTGRES_PASSWORD: ge_pass_2026
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - db
    environment:
      POSTGRES_DB: gestor_expedientes
      POSTGRES_USER: ge_user
      POSTGRES_PASSWORD: ge_pass_2026
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      DJANGO_SECRET_KEY: 3$&8#s82gwq-a4c(ipcld$@4b0m!6vez3v*sjj#w-v(7bhi^uo
      DEBUG: "True"
      CORS_ALLOWED_ORIGINS: "http://localhost:3000,http://localhost:5173"
    ports:
      - "8000:8000"
    volumes:
      - media:/app/media
      - ./backend:/app

  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  pgdata:
  media:
