# Generated by Django 6.0.2 on 2026-05-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_types', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='is_required',
            field=models.BooleanField(default=False, help_text='Si es True, este documento es obligatorio para enviar a revision'),
        ),
    ]
