# Generated by Django 4.2.20 on 2026-02-08 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedients', '0004_alter_expedient_status'),
        ('document_types', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('path', models.CharField(help_text='Ruta absoluta o relativa en el servidor', max_length=500)),
                ('docname', models.CharField(help_text='Nombre real del archivo en el sistema', max_length=255)),
                ('description_state', models.CharField(blank=True, max_length=100, null=True)),
                ('description_content', models.TextField(blank=True, null=True)),
                ('description_corrections', models.TextField(blank=True, null=True)),
                ('approval_status', models.BooleanField(default=False)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='document_types.documenttype')),
                ('expedient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='expedients.expedient')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
