# Generated by Django 4.2.20 on 2026-04-07 23:46

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docname',
            field=models.CharField(blank=True, help_text='Nombre original del archivo', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=documents.models.document_upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='path',
            field=models.CharField(blank=True, help_text='Ruta relativa del archivo en el servidor', max_length=500),
        ),
    ]
