# Generated by Django 4.2.20 on 2026-04-25 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_docname_alter_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='approval_status',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
