# Generated by Django 4.2.20 on 2026-07-19 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_set_pending_as_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pending_update_request',
            field=models.BooleanField(default=False),
        ),
    ]
