# Generated by Django 4.2.20 on 2025-01-27 00:01

from django.db import migrations


def create_roles_and_admin(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    UsersCustom = apps.get_model('users', 'UsersCustom')
    
    # Create roles
    admin_role = Role.objects.create(
        name='admin',
        description='Administrador del sistema con acceso completo'
    )
    Role.objects.create(
        name='analyst',
        description='Analista que puede revisar y validar expedientes'
    )
    Role.objects.create(
        name='employee',
        description='Empleado que puede subir y gestionar sus expedientes'
    )
    Role.objects.create(
        name='user',
        description='Usuario normal con acceso básico'
    )
    
    # Create admin user using create_user to properly hash password
    admin_user = UsersCustom.objects.create_user(
        username='admin',
        email='admin@sistema.com',
        password='123asdP$',
        cedula='00000000',
        phone='00000000000',
        is_staff=True,
        is_superuser=True,
        is_active=True,
        role=admin_role
    )


def reverse_func(apps, schema_editor):
    Role = apps.get_model('users', 'Role')
    UsersCustom = apps.get_model('users', 'UsersCustom')
    
    UsersCustom.objects.filter(username='admin').delete()
    Role.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_role'),
    ]

    operations = [
        migrations.RunPython(create_roles_and_admin, reverse_func)
    ]