# Generated by Django 4.2.20 on 2026-05-25 12:11

from django.db import migrations, models


def migrate_role_to_rol(apps, schema_editor):
    UsersCustom = apps.get_model('users', 'UsersCustom')
    Role = apps.get_model('users', 'Role')
    for user in UsersCustom.objects.all():
        if user.role_id:
            role_name = Role.objects.get(id=user.role_id).name
            if role_name in ['admin', 'analyst', 'employee']:
                user.rol = role_name
            else:
                user.rol = 'employee'
        user.cuenta_activa = user.is_active
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_seed_roles_and_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userscustom',
            name='clave_temporal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userscustom',
            name='cuenta_activa',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userscustom',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('analyst', 'Analista'), ('employee', 'Empleado')], default='employee', max_length=20),
        ),
        migrations.AlterField(
            model_name='userscustom',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.RunPython(migrate_role_to_rol, migrations.RunPython.noop),
    ]
