# Generated by Django 6.0.5 on 2026-06-03 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_seed_roles_and_sync'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userscustom',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
