# Generated by Django 4.2.20 on 2026-06-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userscustom_role_delete_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscustom',
            name='rol',
            field=models.CharField(choices=[('admin', 'Administrador'), ('analyst', 'Analista'), ('recepcionista', 'Recepcionista')], default='recepcionista', max_length=20),
        ),
    ]
