# Generated by Django 4.2.20 on 2025-07-31 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expediente',
            name='identificador',
        ),
        migrations.RemoveField(
            model_name='expediente',
            name='numero_de_documentos',
        ),
    ]
