# Generated by Django 6.0.1 on 2026-01-29 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('document_types', '0001_initial'),
        ('documentos', '0002_remove_expediente_identificador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='document_types.documenttype'),
        ),
        migrations.AddField(
            model_name='documento',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='departments.department'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='nombre_referencia',
            field=models.CharField(blank=True, help_text='Nombre de referencia si no hay usuario ligado', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='expediente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes', to=settings.AUTH_USER_MODEL),
        ),
    ]
