# Generated by Django 4.2.20 on 2026-02-01 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documentos', '0003_documento_tipo_documento_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expediente',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedientes_documentos', to='departments.department'),
        ),
        migrations.AlterField(
            model_name='expediente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_documentos', to=settings.AUTH_USER_MODEL),
        ),
    ]
