# Generated by Django 4.2.20 on 2026-02-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedients', '0002_alter_expedient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedient',
            name='status',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Finalizado', 'Finalizado'), ('Rechazado', 'Rechazado')], default='Pendiente', max_length=20),
        ),
    ]
