# Generated by Django 4.2.20 on 2026-04-07 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('expedients', '0004_alter_expedient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedient',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expedientes', to='departments.department'),
        ),
    ]
