# Generated by Django 6.0.2 on 2026-05-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedients', '0004_alter_expedient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedient',
            name='is_draft',
            field=models.BooleanField(default=True, help_text='Si es True, el analista no puede ver este expediente'),
        ),
    ]
