# Generated by Django 4.2.20 on 2026-05-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expedients', '0005_expedient_department'),
        ('expedients', '0005_expedient_is_draft'),
    ]

    operations = [
    ]
