# Generated by Django 4.2.20 on 2026-05-05 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expedients', '0006_merge_20260504_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedient',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='Aprobado por'),
        ),
        migrations.AddField(
            model_name='expedient',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_rechazados', to=settings.AUTH_USER_MODEL, verbose_name='Rechazado por'),
        ),
    ]
