# Generated by Django 6.0.2 on 2026-05-10 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedients', '0007_expedient_approved_by_expedient_rejected_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedient',
            name='status',
            field=models.CharField(choices=[('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Proceso', 'Proceso'), ('Finalizado', 'Finalizado'), ('Rechazado', 'Rechazado'), ('Pre_Aprobado', 'Pre-Aprobado')], default='Pendiente', max_length=20),
        ),
    ]
