# Generated by Django 4.2.20 on 2026-05-29 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('expedients', '0009_expedient_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedient',
            name='asinged_to',
            field=models.ForeignKey(limit_choices_to={'rol': 'employee'}, on_delete=django.db.models.deletion.CASCADE, related_name='expedientes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
    ]
