# Generated by Django 4.2.20 on 2026-06-08 03:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedients', '0010_alter_expedient_asinged_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expedient',
            name='has_pending_updates',
            field=models.BooleanField(default=False, help_text='Indica si el expediente aprobado tiene documentos nuevos sin revisar'),
        ),
        migrations.AlterField(
            model_name='expedient',
            name='asinged_to',
            field=models.ForeignKey(limit_choices_to={'rol': 'recepcionista'}, on_delete=django.db.models.deletion.CASCADE, related_name='expedientes_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado a'),
        ),
        migrations.AlterField(
            model_name='expedient',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='expedient',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=True, help_text='Si es True, el analista no puede ver este expediente'),
        ),
        migrations.AlterField(
            model_name='expedient',
            name='status',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('Aprobado', 'Aprobado'), ('Pendiente', 'Pendiente'), ('Proceso', 'Proceso'), ('Finalizado', 'Finalizado'), ('Rechazado', 'Rechazado'), ('Pre_Aprobado', 'Pre-Aprobado')], db_index=True, default='Pendiente', max_length=20),
        ),
    ]
