# Generated by Django 4.2.20 on 2026-07-20 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedients', '0011_expedient_has_pending_updates_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedient',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Razón del rechazo del expediente', null=True),
        ),
    ]
